### ISSUE TITLE
Upgrade tar version

### ISSUE THREAD

**Issue by alexanderdickson** [dcodeIO/ClosureCompiler.js#41]
The current version of `tar` being used has a vulnerability.

> ### Overview
> 
> The tar module earlier than version 2.0.0 allow for archives to contain symbolic links that will overwrite targets outside the expected path for extraction.
> 
> ### Remediation
> 
> Update to a version 2.0.0 or greater

https://nodesecurity.io/advisories/57

**Comment by dcodeIO** [comment]
`"tar": "~2.2.1",`
